### ISSUE TITLE
ADD About us in Settings menu

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/android-productivity-timer-tametu-app#23]
Must have an option of About US that help the users to know the motive and purpose behind the app and details about the creation team.
### Expected behaviour
Add option of About US in Settings menu 
### Actual behaviour
No option of such kind till date .

### Would you like to work on the issue?

Tell us if you would like to work on this issue

yes 
it would be a great to work on this issue if given necessary details to implement.
-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
This is a great idea @chanmol1999!

Which all information would you need for this?

As far as I understand you'll need information on 
1. Creation Team: _Students of Google India Udacity Scholarship & NJACK Winter of Code Participants_
2. Motive was to have a Pomodoro better than what is already on market. The motive is still the same, but in order to avoid copyright issues, we can't use the term Pomodoro. I can craft this to sound a little better.

anything else?

**Comment by chanmol1999** [comment]
Most probably this much information only

**Comment by numerative** [comment]
We aimed to build a simple productivity timer that is helpful and lovable. Tamétû likes to keep things simple and is therefore an ensemble of just the most required features.

How's this for the about us, @chanmol1999 ?

**Comment by chanmol1999** [comment]
good.
What you suggest it should be a as a spinner of about us in settings or simply a new screen.
