### ISSUE TITLE
Change option not working

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/android-productivity-timer-tametu-app#30]
The change option available in card view is not working as i think it is expected to do some task.

### Would you like to work on the issue?
Tell us if you would like to work on this issue
Yes
if specified exact work to be done by it.
-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by numerative** [comment]
Here is the original issue for the above: #19 

All the text labels will eventually be removed since they don't serve any special purpose.

Hence, instead of clicking on _change_ user should click on the task name to change the task name.

The behaviour must be as described in issue #19. Let me know if you are interested.

**Comment by chanmol1999** [comment]
yes i can try that

**Comment by numerative** [comment]
Cool. I'll be closing this issue. Just leave a comment over #19 that you are working on it.
