### ISSUE TITLE
A dialog box should pop up on pressing back

### ISSUE THREAD

**Issue by chanmol1999** [NJACKWinterOfCode/android-productivity-timer-tametu-app#37]
A confirming dialog box must pop up on pressing back button ; with text do you really want to exit.

### Steps to reproduce
changes in activity. 

### Actual behaviour
no dialog box

### Would you like to work on the issue?
Tell us if you would like to work on this issue
yes
-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by chanmol1999** [comment]
Is this feature worth implementing or not according to @numerative

**Comment by numerative** [comment]
@chanmol1999 I believe that this not a required feature because: it is only a 2-screen app and user can exit only from the home screen. Secondly, we are trying to make this app usable only from the notifications, which encourages users to use the app even when it is not actively occupying the screen.

Do you agree?

**Comment by chanmol1999** [comment]
Yes that's true
