### ISSUE TITLE
Move the About Us text to Settings Activity

### ISSUE THREAD

**Issue by numerative** [NJACKWinterOfCode/android-productivity-timer-tametu-app#59]
Move the About Us text to SettingsActivity and delete the AboutUs Activity.

-----------------------------------

Interested in taking up this issue? Leave a comment expressing your interest.

Each issue expects a 24hr turnaround time by default. In case where a student doesn't come back with an update after 24 hours have elapsed, the issue is *up for grabs* by anyone.

**Comment by ghost** [comment]
I have changed but unable to push it error code 403

**Comment by chanmol1999** [comment]
If instead of moving about us text to settings activity if we put a option of terms of use at the bottom of settings activity alongwith adding a copyright symbol definitely with small font so what are your views regarding that @numerative while the same intent will be used for terms of use just as for about us.

**Comment by ghost** [comment]
yeah @chanmol1999 we can do that

**Comment by chanmol1999** [comment]
> If instead of moving about us text to settings activity if we put a option of terms of use at the bottom of settings activity alongwith adding a copyright symbol definitely with small font so what are your views regarding that @numerative while the same intent will be used for terms of use just as for about us.

What were your views regarding this @numerative.Instead of terms of use it will be About Tametu app.
